import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-red-200 ml-48 h-screen flex justify-center items-center text-center">
          {children}
        </div>
        </body>
    </html>
  )
}